services:

  db:
    image: postgres:13.10
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: artemnikolaich/foodgram_backend
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - redoc:/app/api/docs/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: artemnikolaich/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    restart: always 
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - redoc:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend

volumes:
  db_data:
  static_value:
  media_value:
  redoc: